name: "Bug report"
description: "Report an issue to help the project improve."
title: "bug <title>"
labels:
  - "bug"
  - required: true
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Please enter an explicit description of your issue"
      placeholder: "Short and explicit description of your incident..."
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: "Steps to reproduce the behavior"
      value: |
        1. Go to `...`
        2. Click on `....`
        3. Scroll down to `....`
        4. See error.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem"
      render: markdown
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: "Please copy and paste any relevant log output if available"
      render: markdown
    validations:
      required: false
  - type: input
    id: snapchat-version
    attributes:
      label: "Snapchat Version"
      description: "On which Snapchat version is this happening?"
      placeholder: "ex. 12.35.0.45"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: "Agreement"
      description: "By creating this issue, I agree that:"
      value: |
        I am using the latest stable SnapEnhance version.
        There is no existing issue describing my problem.
        This is not a bug regarding Snapchat+.
        I have provided a detailed description of the issue.
        I have attached a log if the module is failing.
        I have made sure that my issue is easy to read.
        I have attached screenshots if possible.
        I have stated my device's root status and any other relevant information.
        This issue is not a duplicate.
    validations:
      required: true
