name: "Bug report"
description: "Report an issue to help the project improve."
title: "bug: <title>"
labels:
  - "bug"
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Please enter an explicit description of your issue"
      placeholder: "Short and explicit description of your incident..."
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: "Steps to reproduce the behavior"
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: markdown
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem"
      value: |
        ![DESCRIPTION](LINK.png)
      render: markdown
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: "Please copy and paste any relevant log output if available"
      render: markdown
    validations:
      required: false
  - type: input
    id: snapchat-version
    attributes:
      label: "Snapchat Version"
      description: "On which Snapchat version is this happening?"
      placeholder: "ex. 12.35.0.45"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: "Agreement"
      description: "By creating this issue, I made sure that ..."
      options:
        - label: "I am using the latest stable SnapEnhance version."
        - label: "There is no issue already describing my problem."
        - label: "This is not a bug regarding Snapchat+."
        - label: "I have a detailed description."
        - label: "In case of any errors or failures of the functionality of the module, I have a log attached."
        - label: "It's not a pain to read."
        - label: "I have screenshots attached if possible."
        - label: "I have stated (rooted or not, any other modules, etc.)."
        - label: "This issue isn't a duplicate."
    validations:
      required: true
