name: "Bug report"
description: Report an issue to help the project improve.
title: "bug: <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Steps to reproduce the behavior
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output if available
      render: bash
    validations:
      required: false
  - type: input
    id: snapchat-version
    attributes:
      label: "Snapchat Version"
      description: On which Snapchat version is this happening?
      placeholder: ex. 12.35.0.45
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Agreement
      description: By creating this issue I made sure that ...
        label: |
        1. I am using the latest stable SnapEnhance version.
        2. There is no issue already describing my problem.
        3. This is not a bug regarding Snapchat+
        4. I Have a detailed description
        5. In case of any errors, or failures of the functionality of the module, have a log attached
        6. Its not a pain to read
        7. I have Screenshots attached if possible
        8. I have stated (rooted or not, any other modules, etc.)
        9. This issue isnt a duplicate
        required: true
        
