name: Android CI
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '.github/**'
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Clean Gradle Cache
      run: ./gradlew clean
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Upload armv8
      uses: actions/upload-artifact@v3.1.2
      with:
        name: app-armv8-release
        path: app/build/outputs/apk/armv8/debug/*.apk
    - name: Upload armv7
      uses: actions/upload-artifact@v3.1.2
      with:
        name: app-armv7-release
        path: app/build/outputs/apk/armv7/debug/*.apk
    - name: Upload prod
      uses: actions/upload-artifact@v3.1.2
      with:
        name: app-prod-release
        path: app/build/outputs/apk/prod/debug/*.apk
