name: Beta CI
on:
  workflow_dispatch:

jobs:
  job_armv8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Grant Execute Permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew assembleArmv8Debug

      - name: Generate Version
        run: ./gradlew getVersion

      - name: Set Version to Environment Variables
        id: version-env
        run: |
          echo "version=$(cat app/build/version.txt)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Git Branch Name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@main

      - name: Rename APK File
        run: |
          mv app/build/outputs/apk/armv8/debug/*.apk app/build/outputs/apk/armv8/debug/SnapEnhance-${{ env.version }}-ARMv8-${{ steps.version-env.outputs.sha_short }}.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SnapEnhance-ARMv8-Debug
          path: app/build/outputs/apk/armv8/debug/*.apk

  job_armv7:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Grant Execute Permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew assembleArmv7Debug

      - name: Generate Version
        run: ./gradlew getVersion

      - name: Set Version to Environment Variables
        id: version-env
        run: |
          echo "version=$(cat app/build/version.txt)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Git Branch Name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@main

      - name: Rename APK File
        run: |
          mv app/build/outputs/apk/armv7/debug/*.apk app/build/outputs/apk/armv7/debug/SnapEnhance-${{ env.version }}-ARMv7-${{ steps.version-env.outputs.sha_short }}.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SnapEnhance-ARMv7-Debug
          path: app/build/outputs/apk/armv7/debug/*.apk

  job_universal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Grant Execute Permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew assembleAllDebug

      - name: Generate Version
        run: ./gradlew getVersion

      - name: Set Version to Environment Variables
        id: version-env
        run: |
          echo "version=$(cat app/build/version.txt)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Git Branch Name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@main

      - name: Rename APK File
        run: |
          mv app/build/outputs/apk/all/debug/*.apk app/build/outputs/apk/all/debug/SnapEnhance-${{ env.version }}-Universal-${{ steps.version-env.outputs.sha_short }}.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SnapEnhance-Universal-Debug
          path: app/build/outputs/apk/all/debug/*.apk

  job_manager:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Grant Execute Permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew manager:assembleDebug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Manager
          path: manager/build/outputs/apk/debug/*.apk

  job_core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Grant Execute Permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew assembleCoreDebug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Core
          path: app/build/outputs/apk/core/debug/*.apk